name: Code Quality on PR

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22.13'

      - name: Install dependencies
        run: npm install

      - name: Execute ESLint
        id: eslint
        run: npx eslint app/src/**/*.ts > eslint-report.txt || true

      - name: Check if ESLint report is empty
        id: check_empty
        run: |
          if [ ! -s eslint-report.txt ]; then
            echo "No linting issues found." > eslint-report.txt
          fi

      - name: Load report ESLint

        uses: actions/upload-artifact@v4

        with:
          name: eslint-report
          path: eslint-report.txt

      - name: Comment PR with ESLint report
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path: eslint-report.txt

      - name: Execute Tests
        id: test
        run: npm run test:report
        working-directory: app

      - name: Check if Test report is empty
        id: check_empty_test
        run: |
          if [ ! -s app/reports/test-report.txt ]; then
            echo "No test issues found." > app/reports/test-report.txt
          fi

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: app/reports/test-report.txt

      - name: Comment PR with Test Report
        if: always()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path: app/reports/test-report.txt
          header: Test Report
          

      - name: Fail if tests failed
        if: failure()
        run: exit 1     
